# Generated by Django 4.2 on 2025-12-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('food', 'Food 🍔'), ('travel', 'Travel ✈️'), ('rent', 'Rent 🏠'), ('shopping', 'Shopping 🛍️'), ('bills', 'Bills 📄'), ('others', 'Others ✨')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
